[package]
name = "mapgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rand = "0.8.4"
base64 = "0.13.0"
clap = { version = "3.0.12", features = ["derive"] }